### ISSUE TITLE
Header and footer bar border cannot be none

### ISSUE THREAD

**Issue by mrextreme** [jquery/themeroller.jquerymobile.com#206]
Currently the exact same class is applied to page header, list header and weirdly enough even to the slider: there MUST be border (edit Header/Footer Bar "border" in a swatch and see it for yourself). This is just wrong, especially for the page header and footer, because that means there will be a 1px line between the edge of the screen and the edge of the header. We have to manually override it with

```
.ui-header
{
    border: none !important;
}
```

**Comment by jaspermdegroot** [comment]
@mrextreme 

To reduce CSS we use same classes for multiple widgets. The 1px border is part of the structure. If you don't want a border you can simply override it with custom CSS like you showed. I don't see why this is wrong.

I am closing this ticket because it's not a ThemeRoller issue.
