### ISSUE TITLE
Pop up on Kuler colors is unreachable

### ISSUE THREAD

**Issue by agcolom** [jquery/themeroller.jquerymobile.com#217]
When hovering over a Kuler color name, a popup comes up with a link saying "view on kuler.com", however, the popup disappears as soon as you move out of the color name. As a result, you can never reach that popup to click on the link. 
Tested on Mac OSX 10.7.5, FF 35.0.1, Safari 6.1.6, Chrome 40.

**Comment by jaspermdegroot** [comment]
@agcolom 

This is generated by the Kuler API that we use so we can't fix this.

I'm not sure if they are still maintaining this old API now Adobe Kuler has become Adobe Color CC. Can't find a site where you can report bugs and documentation is gone too. See https://wikidocs.adobe.com/wiki/display/kulerdev/A.+Documentation.

Something to look into for the new ThemeRoller. Closing this ticket as can't fix.
