### ISSUE TITLE
Themeroller does not optimise outputted images

### ISSUE THREAD

**Issue by strikernl** [jquery/themeroller.jquerymobile.com#219]
I'm not sure if this is even really an issue, just something I noticed (it may not be themeroller centric either):

The PNGs outputted by themeroller, for example the icons, are not optimised, for example:

https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/images/ui-icons_222222_256x240.png

Gives the following in Google Pagespeed Insights:

```
Consider Fixing:
Optimize images
Properly formatting and compressing images can save many bytes of data.
Optimize the following images to reduce their size by 2.5KiB (37% reduction).
Losslessly compressing https://ajax.googleapis.com/…hness/images/ui-icons_222222_256x240.png could save 2.5KiB (37% reduction).
```

See: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjqueryui%2F1.11.3%2Fthemes%2Fsmoothness%2Fimages%2Fui-icons_222222_256x240.png&tab=desktop

No big deal, just thought I'd mention it ;)

**Comment by jaspermdegroot** [comment]
@strikernl - This is the issue tracker of the jQuery Mobile ThemeRoller, not jQuery UI. You can open a ticket for it [here](http://bugs.jqueryui.com/).

**Comment by strikernl** [comment]
Thank you @jaspermdegroot
