### ISSUE TITLE
Remove bullseye from the themeroller landing page

### ISSUE THREAD

**Issue by agcolom** [jquery/themeroller.jquerymobile.com#223]
we should remove the bullseye from the landing page and push the div with class="colors" to the right on the popup so that it is aligned with the text above it

**Comment by arschmitz** [comment]
The bullseye has been gone for quite some time now 
![image](https://cloud.githubusercontent.com/assets/462993/10941610/53f899ee-82da-11e5-9820-a98cb5aaa6d4.png)

I agree we should move the color chart to align with the text though

**Comment by agcolom** [comment]
@arschmitz There is still one on the landing page (see just behind the popup), below the  "Drag a color".

**Comment by cgack** [comment]
@arschmitz @agcolom there are a few other places the target/bullseye exists as well (import, download, share, and help popups). I can take this and create a PR for it, along with the alignment issue

**Comment by arschmitz** [comment]
@cgack awesome sounds good thank you

**Comment by cgack** [comment]
this is ready for review
