### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by acha5066** [jquery/themeroller.jquerymobile.com#225]
Import of a previously downloaded, non-minified css file loads the visual styles in the theme roller ui, however the modal overlay does not go away unless you click cancel.

The hex codes in the style picker on the left seem to be the default settings, while the UI itself is my theme.

I get the following in my console.

``` javascript
Error: Uncaught TypeError: Cannot read property '1' of null on line 1611 of app.js 
```

which is the code: 

``` javascript
//Function to convert hex format to a rgba color
TR.rgbatohex = function(rgba) {
    rgba = rgba.match(/^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$/);
    return "#" + TR.hex(rgba[1]) + TR.hex(rgba[2]) + TR.hex(rgba[3]);
}
```

Also, I imported successfully with the default theme, which is strange as I never changed my custom file after I downloaded it from the themeroller.

**Comment by agcolom** [comment]
@acha5066 I've just tried and successfully imported a previously created theme into themeroller and did not get any issues with the overlay. Are you still experiencing this issue? I'm on a Mac OSX 10.7.5, and Chrome 46.

**Comment by agcolom** [comment]
@acha5066 Also double checked the hex values and all seems fine, also not getting an error in the console.

**Comment by acha5066** [comment]
I just tried again with a different theme and it worked. Not sure what happened with the old one. Maybe it was just 1 in a million.

**Comment by agcolom** [comment]
@acha5066 Thank you very much for checking :-)
