### ISSUE TITLE
Chrome themeroller mixed up

### ISSUE THREAD

**Issue by vankampenp** [jquery/themeroller.jquerymobile.com#228]
Hi I am using Chrome Version "46.0.2490.86 m". 
The display of the theme roller in Chrome is completely off. The pop-up's and help text appear at the top, lots of the markup of the theme roller itself is missing. The inspector is not working, etc etc. It works well in IE 11. 

Thanks, Pieter

![image](https://cloud.githubusercontent.com/assets/16002371/11374317/c2d15652-92d5-11e5-94a1-bf2344cf0edd.png)

**Comment by agcolom** [comment]
@vankampenp On which OS are you seeing this? Thanks. (I'm not seeing the issue with OSX 10.7.5 and same v of Chrome (except for the 64-bit: Version 46.0.2490.86 (64-bit))

**Comment by vankampenp** [comment]
This is on Windows 8.1 64 bit Chrome 46 and 47.0.2526.73 m
